Repository Choices-js/Choices, pull requests merged in 2019-11, with the labels that each got.

#715 [TEST] Automatic screenshots comparing and error checking in IE11, Firefox and Chrome
  .gitattributes
  .github/actions-scripts/__snapshots__/chrome-win32.png
  .github/actions-scripts/__snapshots__/firefox-darwin.png
  .github/actions-scripts/__snapshots__/firefox-win32.png
  .github/actions-scripts/__snapshots__/ie-win32.png
  .github/actions-scripts/__snapshots__/puppeteer-darwin.png
  .github/actions-scripts/__snapshots__/safari-darwin.png
  .github/actions-scripts/puppeteer.js
  .github/actions-scripts/selenium.js
  .github/workflows/browsers.yml
  .prettierrc.json
  server.js
Labels: chore

#730 fix setChoices flow
  public/assets/scripts/.eslintrc.js
  src/scripts/choices.js
  src/scripts/choices.test.js
Labels: bugfix

#731 Fix #727
  .github/actions-scripts/__snapshots__/puppeteer-darwin.png
  .github/release-drafter.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/release-drafter.yml
  README.md
  cypress/integration/select-multiple.spec.js
  cypress/integration/select-one.spec.js
  cypress/integration/text.spec.js
  public/assets/styles/choices.css
  public/assets/styles/choices.min.css
  public/test/select-multiple/index.html
  public/test/select-one/index.html
  public/test/text/index.html
  src/scripts/choices.js
  src/scripts/choices.test.js
  src/scripts/templates.js
Labels: breaking change

#734 Add missing type definitions + rename sortFn
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  jsconfig.json
  src/scripts/actions/choices.js
  src/scripts/actions/general.js
  src/scripts/actions/general.test.js
  src/scripts/actions/groups.js
  src/scripts/actions/groups.test.js
  src/scripts/actions/items.js
  src/scripts/actions/items.test.js
  src/scripts/actions/misc.js
  src/scripts/actions/misc.test.js
  src/scripts/choices.js
  src/scripts/choices.test.js
  src/scripts/components/container.js
  src/scripts/components/dropdown.js
  src/scripts/components/input.js
  src/scripts/components/list.js
  src/scripts/components/wrapped-element.js
  src/scripts/components/wrapped-element.test.js
  src/scripts/components/wrapped-input.js
  src/scripts/components/wrapped-select.js
  src/scripts/constants.js
  src/scripts/lib/utils.js
  src/scripts/store/store.js
  src/scripts/store/store.test.js
  types/index.d.ts
Labels: breaking change

#735 Code refactoring
  package-lock.json
  package.json
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/index.html
  src/scripts/actions/choices.js
  src/scripts/actions/groups.js
  src/scripts/actions/items.js
  src/scripts/actions/misc.js
  src/scripts/choices.js
  src/scripts/choices.test.js
  src/scripts/components/container.js
  src/scripts/components/input.js
  src/scripts/components/list.js
  src/scripts/lib/delegate-events.js
  src/scripts/lib/utils.js
  src/scripts/lib/utils.test.js
  src/scripts/store/store.js
  types/index.d.ts
Labels: refactor

#739 Resolve bug 473
  cypress/integration/select-one.spec.js
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/test/select-one/index.html
  src/scripts/choices.js
Labels: bugfix

#743 Fix id types
  package-lock.json
  public/assets/images/browserconfig.xml
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  src/scripts/choices.js
  src/scripts/choices.test.js
  src/scripts/components/list.js
  src/scripts/lib/utils.js
  src/scripts/store/store.js
  src/scripts/store/store.test.js
  types/index.d.ts
Labels: chore

#740 improve whole-page performance by scoping events handlers
  src/scripts/choices.js
  src/scripts/lib/utils.js
  src/scripts/lib/utils.test.js
Labels: refactor

#754 Resolve bug #637
  README.md
  src/scripts/constants.js
  src/scripts/constants.test.js
  src/scripts/templates.js
  src/scripts/templates.test.js
  types/index.d.ts
Labels: bugfix

#755 Remove redundant check
  cypress/integration/select-one.spec.js
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/assets/styles/choices.css
  public/assets/styles/choices.min.css
  src/scripts/choices.js
  src/scripts/templates.test.js
Labels: bugfix

#758 🔖 Version 9.0.0
  package-lock.json
  package.json
Labels: release

#761 Fix releases
  .github/workflows/deployment.yml
Labels: chore

#574 Fix #573
  cypress/integration/select-one.spec.js
  public/test/select-one/index.html
  src/scripts/choices.js
Labels: bugfix

#763 Next release
  package-lock.json
  package.json
Labels: release

#765 Update polyfill list
  .eslintrc.json
  README.md
  public/index.html
  src/scripts/choices.js
  types/index.d.ts
Labels: chore

#767 Resolve #762
  cypress/integration/select-one.spec.js
  public/assets/styles/choices.css
  public/assets/styles/choices.min.css
  src/scripts/choices.js
  src/scripts/choices.test.js
  src/styles/choices.scss
Labels: bugfix

#777 Resolve 774
  .github/workflows/browsers.yml
  .nvmrc
  README.md
  src/scripts/actions/items.js
  src/scripts/choices.js
  src/scripts/choices.test.js
Labels: bugfix

#784 Resolve #622 and #781
  README.md
  package-lock.json
  package.json
  public/index.html
  src/scripts/choices.js
Labels: chore
