Repository Choices-js/Choices, pull requests merged in 2019-12, with the labels that each got.

#785 Resolve #780
  .github/actions-scripts/__snapshots__/puppeteer-darwin.png
  public/assets/styles/choices.css
  public/assets/styles/choices.min.css
  src/styles/choices.scss
Labels: bugfix

#794 Adds a variable for the z-index
  src/styles/choices.scss
Labels: housekeeping

#800 Update release drafter to latest
  .github/workflows/release-drafter.yml
Labels: chore
