Repository Choices-js/Choices, pull requests merged in 2021-12, with the labels that each got.

#975 Fix broken demo link in README.md
  README.md
Labels: documentation

#873 Documentation of input type terms
  README.md
Labels: documentation

#979 Switch to dart-sass, fix npm audit issues
  .github/workflows/lint.yml
  .stylelintrc.json
  .vscode/settings.json
  package-lock.json
  package.json
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/assets/styles/base.css
  public/assets/styles/base.css.map
  public/assets/styles/base.min.css
  public/assets/styles/choices.css
  public/assets/styles/choices.css.map
  public/assets/styles/choices.min.css
  public/index.html
  src/styles/base.scss
  src/styles/choices.scss
Labels: chore

#983 Fix Sanitization of > Characters
  src/scripts/components/input.test.ts
  src/scripts/lib/utils.test.ts
  src/scripts/lib/utils.ts
Labels: bugfix

#908 Enhance inputCloned text input with type and name
  src/scripts/templates.test.ts
  src/scripts/templates.ts
Labels: bugfix

#984 feat: Introduce allowHTML option to allow people to disable injecting HTML into choices.
  README.md
  cypress/integration/select-multiple.spec.ts
  cypress/integration/select-one.spec.ts
  cypress/integration/text.spec.ts
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/index.html
  public/test/select-multiple/index.html
  public/test/select-one/index.html
  public/test/text/index.html
  src/scripts/choices.test.ts
  src/scripts/choices.ts
  src/scripts/constants.test.ts
  src/scripts/defaults.ts
  src/scripts/interfaces/options.ts
  src/scripts/templates.test.ts
  src/scripts/templates.ts
Labels: feature request, breaking change

#989 Update GitHub Actions
  .github/actions-scripts/puppeteer.js
  .github/workflows/browsers.yml
  .github/workflows/build-and-test.yml
  .github/workflows/bundlesize.yml
  .github/workflows/deployment.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/lint.yml
  .github/workflows/polyfills-sync.yml
  .github/workflows/unit-tests.yml
Labels: chore
