Repository Choices-js/Choices, pull requests merged in 2022-01, with the labels that each got.

#992 Trigger search when clearing the input field with search floor of 0
  src/scripts/choices.test.ts
  src/scripts/choices.ts
Labels: bugfix

#991 Upgrade to Fuse v6
  README.md
  package-lock.json
  package.json
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/types/src/scripts/choices.d.ts.map
  public/types/src/scripts/components/input.d.ts
  public/types/src/scripts/components/input.d.ts.map
  public/types/src/scripts/interfaces/choice.d.ts
  public/types/src/scripts/interfaces/choice.d.ts.map
  public/types/src/scripts/interfaces/options.d.ts
  public/types/src/scripts/interfaces/options.d.ts.map
  src/scripts/choices.test.ts
  src/scripts/choices.ts
  src/scripts/interfaces/options.ts
  tsconfig.json
Labels: feature request, breaking change

#996 Fix multiple select in Internet Explorer 11
  src/styles/choices.scss
Labels: bugfix

#1000 README Fix: Use select-single everywhere, fix missing comma in default options
  README.md
Labels: documentation

#971 Add option labelId to improve a11y
  README.md
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/index.html
  public/types/src/scripts/choices.d.ts.map
  public/types/src/scripts/defaults.d.ts.map
  public/types/src/scripts/interfaces/options.d.ts
  public/types/src/scripts/interfaces/options.d.ts.map
  public/types/src/scripts/templates.d.ts
  public/types/src/scripts/templates.d.ts.map
  src/scripts/choices.ts
  src/scripts/defaults.ts
  src/scripts/interfaces/options.ts
  src/scripts/templates.test.ts
  src/scripts/templates.ts
Labels: feature
