Repository Choices-js/Choices, pull requests merged in 2024-09, with the labels that each got.

#1193 Fix regression where webpack doesn't permit importing scss/css
  package.json
Labels: breaking change, bugfix

#1194 Fix regression of UnhighlightItem event not firing (#1173)
  CHANGELOG.md
  src/scripts/choices.ts
  test/scripts/choices.test.ts
Labels: bug

#1192 Fix regression "no choices to choose from"/"no results found" notice did not reliably trigger
  CHANGELOG.md
  src/scripts/choices.ts
  test-e2e/tests/select-multiple.spec.ts
  test-e2e/tests/select-one.spec.ts
Labels: bugfix

#1196 Fix `clearChoices()` would remove items, and clear the search flag
  CHANGELOG.md
  src/scripts/choices.ts
  test/scripts/choices.test.ts
Labels: bugfix

#1197 Fix "no choices' notice was not cleared as expected after search
  src/scripts/choices.ts
Labels: bugfix

#1200 Fix various opt-group handling issues
  CHANGELOG.md
  public/test/select-multiple/index.html
  public/test/select-one/index.html
  src/scripts/choices.ts
  src/scripts/components/wrapped-select.ts
  src/scripts/interfaces/choice-full.ts
  src/scripts/interfaces/event-choice.ts
  src/scripts/interfaces/group-full.ts
  src/scripts/interfaces/input-choice.ts
  src/scripts/interfaces/input-group.ts
  src/scripts/interfaces/types.ts
  src/scripts/lib/choice-input.ts
  src/scripts/lib/utils.ts
  src/scripts/reducers/choices.ts
  src/scripts/reducers/items.ts
  src/scripts/templates.ts
  test-e2e/tests/select-multiple.spec.ts
  test-e2e/tests/select-one.spec.ts
  test/scripts/choices.test.ts
  test/scripts/reducers/choices.test.ts
  test/scripts/reducers/items.test.ts
  test/scripts/store/store.test.ts
  test/scripts/templates.test.ts
Labels: bugfix
