Repository Choices-js/Choices, pull requests merged in 2025-02, with the labels that each got.

#1260 Fix `tab` => direction keys handling with disabled search
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/assets/scripts/choices.mjs
  public/assets/scripts/choices.search-basic.js
  public/assets/scripts/choices.search-basic.min.js
  public/assets/scripts/choices.search-basic.mjs
  public/assets/scripts/choices.search-prefix.js
  public/assets/scripts/choices.search-prefix.min.js
  public/assets/scripts/choices.search-prefix.mjs
  src/scripts/choices.ts
Labels: bugfix

#1265 Fix: Clear button reverses items order
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/test/select-one/index.html
  src/scripts/choices.ts
  test-e2e/tests/select-one.spec.ts
Labels: bugfix

#1266 Do not preventDefault on item to support dragging
  src/scripts/choices.ts
Labels: feature

#1269 Fix: Disabled options are not visible (#1257)
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/assets/scripts/choices.mjs
  public/test/disabled-data.json
  public/test/select-one/index.html
  src/scripts/choices.ts
  test-e2e/select-test-suit.ts
  test-e2e/tests/select-one.spec.ts
Labels: bugfix

#1270 Fix: Reached maximum item limit notice is not cleared after removing selections
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/assets/scripts/choices.mjs
  public/assets/scripts/choices.search-basic.js
  public/assets/scripts/choices.search-basic.min.js
  public/assets/scripts/choices.search-basic.mjs
  public/assets/scripts/choices.search-prefix.js
  public/assets/scripts/choices.search-prefix.min.js
  public/assets/scripts/choices.search-prefix.mjs
  public/test/select-multiple/index.html
  src/scripts/choices.ts
  test-e2e/test-suit.ts
  test-e2e/tests/select-multiple.spec.ts
Labels: bugfix

#1271 Fix v11 regression where `duplicateItemsAllowed` option did not work with `select-one`/`select-multiple`
  README.md
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/assets/scripts/choices.mjs
  public/assets/scripts/choices.search-basic.js
  public/assets/scripts/choices.search-basic.min.js
  public/assets/scripts/choices.search-basic.mjs
  public/assets/scripts/choices.search-prefix.js
  public/assets/scripts/choices.search-prefix.min.js
  public/assets/scripts/choices.search-prefix.mjs
  public/test/select-multiple/index.html
  public/test/select-one/index.html
  public/types/src/scripts/interfaces/options.d.ts
  src/scripts/choices.ts
  src/scripts/interfaces/options.ts
  test-e2e/tests/select-multiple.spec.ts
  test-e2e/tests/select-one.spec.ts
Labels: bugfix

#1272 Fix v11 regression where `clearChoices` (and `setChoices` with `replaceChoices:true`) did not remove selected items
  README.md
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/assets/scripts/choices.mjs
  public/assets/scripts/choices.search-basic.js
  public/assets/scripts/choices.search-basic.min.js
  public/assets/scripts/choices.search-basic.mjs
  public/assets/scripts/choices.search-prefix.js
  public/assets/scripts/choices.search-prefix.min.js
  public/assets/scripts/choices.search-prefix.mjs
  src/scripts/choices.ts
Labels: bugfix

#1273 Fix v11 regression for disabled placeholder option handling
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/assets/scripts/choices.mjs
  public/assets/scripts/choices.search-basic.js
  public/assets/scripts/choices.search-basic.min.js
  public/assets/scripts/choices.search-basic.mjs
  public/assets/scripts/choices.search-prefix.js
  public/assets/scripts/choices.search-prefix.min.js
  public/assets/scripts/choices.search-prefix.mjs
  public/types/src/scripts/store/store.d.ts
  src/scripts/choices.ts
  src/scripts/store/store.ts
Labels: bugfix

#1274 Fix `renderSelectedChoices` option when all choices are selected
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/assets/scripts/choices.mjs
  public/assets/scripts/choices.search-basic.js
  public/assets/scripts/choices.search-basic.min.js
  public/assets/scripts/choices.search-basic.mjs
  public/assets/scripts/choices.search-prefix.js
  public/assets/scripts/choices.search-prefix.min.js
  public/assets/scripts/choices.search-prefix.mjs
  public/test/select-multiple/index.html
  public/test/select-one/index.html
  src/scripts/choices.ts
  test-e2e/tests/select-multiple.spec.ts
  test-e2e/tests/select-one.spec.ts
Labels: bugfix

#1276 Fix v11 `setChoice` performance regression
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/assets/scripts/choices.mjs
  public/assets/scripts/choices.search-basic.js
  public/assets/scripts/choices.search-basic.min.js
  public/assets/scripts/choices.search-basic.mjs
  public/assets/scripts/choices.search-prefix.js
  public/assets/scripts/choices.search-prefix.min.js
  public/assets/scripts/choices.search-prefix.mjs
  public/test/select-multiple/index-performance.html
  public/types/src/scripts/choices.d.ts
  src/scripts/choices.ts
  test-e2e/tests/select-multiple-performance.spec.ts
  test/scripts/choices.test.ts
Labels: bugfix

#1279 Fix setChoices regression, fixes #1278
  README.md
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/assets/scripts/choices.mjs
  public/assets/scripts/choices.search-basic.js
  public/assets/scripts/choices.search-basic.min.js
  public/assets/scripts/choices.search-basic.mjs
  public/assets/scripts/choices.search-prefix.js
  public/assets/scripts/choices.search-prefix.min.js
  public/assets/scripts/choices.search-prefix.mjs
  public/types/src/scripts/choices.d.ts
  src/scripts/choices.ts
Labels: bugfix

#1282 Revert "Do not preventDefault on item to support dragging" #1266
  src/scripts/choices.ts
Labels: bugfix

#1283 Fix setChoices & clearChoices related regressions
  README.md
  public/assets/scripts/choices.js
  public/assets/scripts/choices.min.js
  public/assets/scripts/choices.mjs
  public/assets/scripts/choices.search-basic.js
  public/assets/scripts/choices.search-basic.min.js
  public/assets/scripts/choices.search-basic.mjs
  public/assets/scripts/choices.search-prefix.js
  public/assets/scripts/choices.search-prefix.min.js
  public/assets/scripts/choices.search-prefix.mjs
  public/test/select-multiple/index.html
  public/test/select-one/index.html
  public/types/src/scripts/choices.d.ts
  src/scripts/choices.ts
  test-e2e/tests/select-multiple.spec.ts
  test-e2e/tests/select-one.spec.ts
Labels: breaking change, bugfix
